import json
import os
import sys
import requests

from ai.memory.memory_store import record_pr


def post_pr_comment(repo: str, pr_number: str, token: str, message: str):
    """
    Post a comment to a GitHub Pull Request
    """
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json"
    }

    payload = {"body": message}

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code != 201:
        print("ERROR: Failed to post PR comment")
        print("Status Code:", response.status_code)
        print("Response:", response.text)
        sys.exit(1)

    print("SUCCESS: AI review comment posted to PR")


def build_comment(review: dict) -> str:
    """
    Build a Staff-level, production-quality PR review comment
    """

    environment = review.get("environment", "unknown")
    risk = review.get("risk_level", "UNKNOWN")
    confidence = int(review.get("confidence", 0) * 100)

    reasons = review.get("reasons", [])
    comments = review.get("review_comments", [])
    recommendations = review.get("recommendations", [])
    llm_explanation = review.get("llm_explanation", "")

    comment_body = f"""
## 🤖 AI Terraform Review (Azure)

**Environment:** `{environment}`  
**Risk Level:** `{risk}`  
**Confidence:** `{confidence}%`

---

### 🔍 Why this change is risky
{chr(10).join(f"- {r}" for r in reasons) if reasons else "- No significant risk signals detected."}

---

### 💬 Review Comments
{chr(10).join(f"- {c}" for c in comments) if comments else "- No additional review comments."}

---

### ✅ Recommended Actions
{chr(10).join(f"- {rec}" for rec in recommendations) if recommendations else "- No specific actions required."}
"""

    # Optional LLM explanation
    if llm_explanation:
        comment_body += f"""

---

### 🧠 AI Reasoning (LLM-Assisted)
{llm_explanation}
"""

    # Footer
    comment_body += """
---
_Automated Azure-aware review generated by AI Terraform Reviewer  
Deterministic rules decide. LLM assists explanation only._
"""

    return comment_body


def main():
    # Required GitHub environment variables
    repo = os.environ.get("GITHUB_REPOSITORY")
    pr_number = os.environ.get("PR_NUMBER")
    token = os.environ.get("GITHUB_TOKEN")

    if not repo or not pr_number or not token:
        print("ERROR: Missing required GitHub environment variables")
        sys.exit(1)

    # Load AI review output
    with open("ai/reasoning/ai_review.json", "r") as f:
        review = json.load(f)

    # Build PR comment
    message = build_comment(review)

    # Post comment to PR
    post_pr_comment(repo, pr_number, token, message)

    # -------------------------------------------------
    # Day 11 — Record PR into Historical Memory
    # -------------------------------------------------
    record_pr(
        pr_number=int(pr_number),
        review=review,
        outcome="merged"  # later days will auto-detect rollback/revert
    )


if __name__ == "__main__":
    main()
